[versions]
lombok = "1.18.30"
spring-boot = "3.5.7"
postgres = "42.7.7"
h2 = "2.4.240"
junit-platform = "1.12.2"

[libraries]
lombok = { module = "org.projectlombok:lombok", version.ref = "lombok" }
spring-boot-starter-web = { module = "org.springframework.boot:spring-boot-starter-web", version.ref = "spring-boot" }
spring-boot-starter-data-jpa = { module = "org.springframework.boot:spring-boot-starter-data-jpa", version.ref = "spring-boot" }
h2 = { module = "com.h2database:h2", version.ref = "h2" }
postgres = { module = "org.postgresql:postgresql", version.ref = "postgres" }
spring-boot-starter-test = { module = "org.springframework.boot:spring-boot-starter-test", version.ref = "spring-boot" }
junit-platform-launcher = { module = "org.junit.platform:junit-platform-launcher", version.ref = "junit-platform" }
